//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace admLicenciasTH.Models
{
    using admLicenciasTH.customV;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class licenciasUsuario
    {
        [Required]
        [dotValidator(ErrorMessage="Rut no existe a nivel de dotación! Verificar rut y formato.")]
        public string rutColaborador { get; set; }
        public string tipoIncidencia { get; set; }
        public string tipoLicencia { get; set; }
        [Required(ErrorMessage = "Fecha emision requerida.")]
        public System.DateTime fechaEmision { get; set; }
        [Required(ErrorMessage = "Fecha inicio requerida.")]
        public System.DateTime fechaInicio { get; set; }
        [Required(ErrorMessage = "Días requeridos, mayor a 1.")]
        [Range(1,180)]
        public int diasLicencia { get; set; }
        [Required(ErrorMessage ="Folio requerido")]
        [StringLength(8)]
        public string numeroFolio { get; set; }
        [Required(ErrorMessage = "Nombre del profesional requerido")]
        public string nombreProfesional { get; set; }
        [Required(ErrorMessage = "Folio requerido")]
        public string rutProfesional { get; set; }
        public string tipoEspecialidad { get; set; }
        public string tipoEspecialista { get; set; }
        public string rutaEvidencia { get; set; }
        public string usuarioCarga { get; set; }
        public System.DateTime usuarioSubida { get; set; }
        public Nullable<System.DateTime> usuarioModifica { get; set; }
        public int idLicencia { get; set; }
    }
}
